config/routes.rb
Rails.application.routes.draw do
  root "pages#home"
  get 'about',to: 'pages#about'
  resources :articles  #,  only: [:index,:show,:new,:create, :edit, :update, :destroy]
  get 'signup', to: 'users#new'
  post 'users', to:'users#create'
  resources :users, except: [:new]

  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'

  resources :categories, except: [:destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/article.rb
class Article < ApplicationRecord
  belongs_to :user
  has_many :article_categories
  has_many :categories, through: :article_categories
  validates :title, presence: true , length: { minimum:6, maximum:100}
  validates :description, presence: true , length: { minimum:10, maximum:300}
end

app/models/article_category.rb
class ArticleCategory < ApplicationRecord
  belongs_to :article
  belongs_to :category
end

app/models/category.rb
class Category < ApplicationRecord
  validates :name, presence: true, length:  { minimum:3, maximum:25   }#validazioni controllo presenza valore
  validates_uniqueness_of :name #@controllo univocità 

  has_many :article_categories
  has_many :articles, through: :article_categories
  

end 

app/models/user.rb
class User < ApplicationRecord
  before_save { self.email = email.downcase }

  has_many :articles, dependent: :destroy
  
  validates :username, presence: true, 
            uniqueness: { case_sensitive: false }, 
            length: {minimum: 3, maximum: 25}
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, 
            uniqueness: { case_sensitive: false }, 
            length: {maximum: 105},
            format: { with: VALID_EMAIL_REGEX}
  has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  helper_method :current_user, :logged_in? #per poterlo usare anche nei layout, altrimenti essendo in questo faile è valido solo per i controller
  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id] 
  end


  def logged_in?
    !!current_user #trasforma oin boollean un valore
  end


  def require_user
    if !logged_in?
      flash[:alert] = "Devi essere loggato per fare questo azione"
      redirect_to login_path
    end
  end

end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  
  before_action :set_article, only: [:show,:edit,:update,:destroy]
  before_action :require_user, except: [:show, :index]
  before_action :require_same_user, only: [:edit, :update, :destroy]


  def show
  
  end

  def index
    @articles = Article.paginate(page: params[:page], per_page: 5)
  end

  def new
    @article = Article.new
  end
   
  def edit

  end

  
  def create
    byebug
    @article = Article.new(article_params)
    @article.user = current_user
    if @article.save
      flash[:notice] = "Articolo salvato correttamente"
      redirect_to article_path(@article) #pesca in automatico l'id dell'articolo appena creato e esegue la route show 
    else
      render 'new'
    end 
  end

  def update

    if @article.update(article_params)
      flash[:notice] = "Articolo aggiornato correttamente"
      redirect_to @article
    else
      render 'edit'
    end

  end

  def destroy

    @article.destroy
    redirect_to articles_path 
  end


  private 
  
  def set_article
    @article =  Article.find(params[:id])
  end


  def article_params
    params.require(:article).permit(:title, :description, :body, :subtitle, category_ids: [])
  end

  def require_same_user
    if current_user != @article.user && !current_user.admin
      flash[:alert] = "tu puoi modficare slamente i tuoi articoli"
      redirect_to @article
    end
  end

end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController

  before_action :require_admin, except: [:index, :show]

  def new 
    @category = Category.new
  end 

  def create
    @category = Category.new(category_params)
    if @category.save
      flash[:notice] = "Category created!"
      redirect_to @category
    else
      render  'new'
    end 
  end 

  def edit
    @category = Category.find(params[:id])
  end 

  def update
    @category = Category.find(params[:id])
    if @category.update(category_params)
      flash[:notice] = "Cat udate succesfully"
      redirect_to @category
    else
      render 'edit'
    end 
  end 


  def index
    @categories = Category.paginate(page: params[:page], per_page: 5)
  end 

  def show
    @category = Category.find(params[:id])
    @articles= @category.articles.paginate(page: params[:page], per_page: 5)
  end 

private 

def category_params
  params.require(:category).permit(:name)
end

def require_admin
  if !(logged_in? && current_user.admin?)
    flash[:alert] = "Only admin can perfom this action"
    redirect_to categories_path
  end
end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  
  def home
    redirect_to articles_path if logged_in?
  end

  def about

  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  
  def new
  end
  
  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      session[:user_id] = user.id
      flash[:notice] = "Loggoed succesfuly"
      redirect_to user
    else
      flash.now[:alert] = "there was something wrng with your login details" 
      render 'new'
    end
      
  end

  def destroy
    session[:user_id] = nil
    flash[:notice] = "Loggoed Out succesfuly"
    redirect_to root_path
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
before_action :set_user, only: [:show, :edit,:update, :destroy]
before_action :require_user, only: [:edit, :update]
before_action :require_same_user , only: [:edit,:update, :destroy]

  def show 
    @articles = @user.articles.paginate(page: params[:page], per_page: 5)
  end

  def new
    @user = User.new 
  end

  def edit
  end

  def index 
    @users =  User.paginate(page: params[:page], per_page: 5)
  end

  def create
    @user = User.new (user_params)
    if @user.save
      session[:user_id]= @user.id #con questa riga inizializzo la varibile di sessione e calcolo come loggato il nuovo utente
      flash[:notice] = "Welcome to the alpha blog #{@user.username}"
      redirect_to articles_path
    else
      render 'new'
    end

  end


  def destroy
    @user.destroy
    session[:user_id] = nil if @user == current_user
    flash[:notice] = "Account e articoli sono stati eliminati correttamente"
    redirect_to articles_path
  end


  def update
    if @user.update(user_params)
      flash[:notice] = "Account aggiornato correttamente!"
      redirect_to @user
    else
      render 'edit'
    end

  end

private
  
  def user_params
    params.require(:user).permit(:username, :email, :password)
  end

  def set_user
    @user = User.find(params[:id])
  end

  def require_same_user
    if current_user != @user
      flash[:alert]="Deve essere lo stesso utente per modificare"
      redirect_to @user
    end
  end

end

app/helpers/application_helper.rb
module ApplicationHelper

  def gravatar_for(user, options = {size: 80})
    email_address = user.email.downcase
    hash = Digest::MD5.hexdigest(email_address)
    size = options[:size]
    gravatar_url="https://www.gravatar.com/avatar/#{hash}?s=#{size}"
    image_tag(gravatar_url,alt: user.username, class: "rounded shadow mx-auto d-block")
  end





end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/articles/_article.html.erb
<div class="conteiner">
  <% @articles.each do |art| %> 
    <div class="row justify-content-md-center">
      <div class="col-8 mt-4">
        <div class="card text-center shadow mb-5 bg-white rounded">
          <div class="card-header font-italic">
           <% if art.user %>
              by <%= link_to art.user.username, user_path(art.user) %>
            <% end %>
            <% if art.categories.any? %>
              <div class="mt-2"> <%= render art.categories %> </div>
            <% end  %>

          </div>
          <div class="card-body">
            <h5 class="card-title"><%= link_to art.title, article_path(art), class:"text-success" %></h5>
            <p class="card-text"><%= truncate(art.description, lenght: 100) %></p>
            <%= link_to "View", article_path(art), class:"btn btn-outline-success" %>
            <% if logged_in? && (art.user == current_user || current_user.admin?)  %>
              <%= link_to "Edit", edit_article_path(art), class:"btn btn-outline-info" %>
              <%= link_to "Delete", article_path(art), class:"btn btn-outline-danger", method: :delete, data: {confirm: "Cancellare questo articolo?" } %>
            <% end %>
          </div>
          <div class="card-footer text-muted">
            <small> Created <%= time_ago_in_words(art.created_at) %> ago, edited <%= time_ago_in_words(art.updated_at) %> ago</small>
          </div>
        </div>
      </div>  
    </div>
  <% end %>
</div>

app/views/articles/_form.html.erb
<div class="conteiner m-4">
  <div class="row justify-content-center">
    <div class="col-10">
      <%= render 'shared/errors', obj: @article %>
      <%= form_with(model: @article , data: {turbo:false} ,class:"shadow p-3 mb-5 bg-info rounded", local: true) do |f|  %>

        <div class="form_group row">
          <%= f.label :title, class: "col-2 col-form-label text-light"  %>
          <div class="col-10">
            <%= f.text_field :title, class: "form-control shadow rounded", placeholder:"Titolo" %> 
          </div>
        </div>
<br>
        <div class="form_group row">
          <%= f.label :description , class: "col-2 col-form-label text-light"  %>
          <div class="col-10">
            <%= f.text_area :description,class: "form-control shadow rounded", rows:10 %>
          </div>
        </div>
<br>
        <div class="form_group row">
          <%= f.label :body , class: "col-2 col-form-label"  %>
          <div class="col-10">
            <%= f.text_area :body,class: "form-control shadow rounded", rows:2 %>
          </div>
        </div>
<br>
        <div class="form_group row">
          <%= f.label :subtitle , class: "col-2 col-form-label"  %>
          <div class="col-10">
            <%= f.text_area :subtitle,class: "form-control shadow rounded" %>
          </div>
        </div>
<br>
        <div class="form_group row">
          <%= f.label :category , class: "col-2 col-form-label"  %>
          <div class="col-10">
            <%= f.collection_select(:category_ids, Category.all,:id, :name, 
                                    {prompt: "Make you selection from the list can be empty"}, 
                                    {multiple: true, size: 3, class: "custom-select shadow rounded"})  %>
          </div>
        </div>
<br>

        <div class="form_group row justify-content-center">
          <%= f.submit class: "btn btn-outline-light btn-lg col-2" %>
        </div>

      <% end %>
      <div class="mb-3">
            <%= link_to 'Return list', articles_path %>
      </div>
    </div>
  </div>
</div>

app/views/articles/edit.html.erb
  <h1 class="text-center mt-4">Edit Article</h1>
  <%= render 'form' %>

app/views/articles/index.html.erb
<h1 class="text-center mt-4">Showing Articles list</h1>

<div class="flickr_pagination">
  <%= will_paginate @articles, :container => false %>
</div>
<%= render 'article'%>
<div class="flickr_pagination mb-4">
  <%= will_paginate @articles, :container => false %>
</div>

app/views/articles/new.html.erb
<h1 class="text-center mt-4">Create Article</h1>

<%= render 'form' %>

app/views/articles/show.html.erb
<h2 class="text-center mt-4">Showing Articles details</details></h2>
<h2 class="text-center mt-4"><%= @article.title  %></h2>

<div class="conteiner">
    <div class="row justify-content-md-center">
      <div class="col-8 mt-4">
        <div class="card text-center shadow mb-5 bg-white rounded">
          <div class="card-header font-italic">
            by <%= @article.user.username %>
            <%= link_to gravatar_for(@article.user), user_path(@article.user) %>
            <% if @article.categories.any? %>
              <div class="mt-2"> <%= render @article.categories %> </div>
            <% end  %>
          </div>
          <div class="card-body">
            <div class="card-text text-left"><%= simple_format(@article.description) %></div>
            <% if logged_in? && (@article.user == current_user || current_user.admin?) %>
              <%= link_to "Edit", edit_article_path(@article), class:"btn btn-outline-info" %>
              <%= link_to "Delete", article_path(@article), class:"btn btn-outline-danger", method: :delete, data: {confirm: "Cancellare questo articolo?" } %>
            <% end %>
          </div>
          <div class="card-footer text-muted">
            <small> Created <%= time_ago_in_words(@article.created_at) %> ago, edited <%= time_ago_in_words(@article.updated_at) %> ago</small>
          </div>
        </div>
      </div>  
    </div>
</div>

app/views/categories/_category.html.erb
<span class="badge badge-pill badge-info mr-1"><%= link_to category.name, category_path(category) %></span>

app/views/categories/_form.html.erb
<div class="conteiner m-4">

  <div class="row justify-content-center">
    <div class="col-10">
      
      <%= render 'shared/errors', obj: @category %>

      <%= form_with(model: @category , data: {turbo:false} ,class:"shadow p-3 mb-5 bg-info rounded", local: true) do |f|  %>

        <div class="form_group row">
          <%= f.label :name, "Category name", class: "col-2 col-form-label text-light"  %>
          <div class="col-10">
            <%= f.text_field :name, class: "form-control shadow rounded", placeholder:"Enter a Catagory name" %> 
          </div>
        </div>
<br>
        <div class="form_group row justify-content-center">
          <%= f.submit class: "btn btn-outline-light btn-lg col-2" %>
        </div>

      <% end %>

    </div>
  </div>
</div>

app/views/categories/edit.html.erb
<h1 class="text-center mt-4">Update catagory</h1>
<div class="container">
  <div class="row justify-content-center">
    <div class="col-10">
      <%= render 'form' %>
    </div>    
    <div class="mb-3">
          <%= link_to 'Return Category list', category_path(@category) %>
    </div>
  </div>  
</div>

app/views/categories/index.html.erb
<h1 class="text-center mt-4">Showing Catagories list</h1>

<div class="flickr_pagination">
  <%= will_paginate @categories, :container => false %>
</div>

<div class="conteiner">
  <% @categories.each do |cat| %> 
    <div class="row justify-content-md-center">
      <div class="col-4 mt-4">
        <div class="card text-center shadow mb-5 bg-white rounded">

          <div class="card-body">
            <h5 class="card-title"><%= link_to cat.name, category_path(cat), class:"text-success" %></h5>
            <p class="card-text"><%= pluralize(cat.articles.count, "article") %></p>
          </div>

          <div class="card-footer text-muted">
            <small> Created <%= time_ago_in_words(cat.created_at) %> ago, edited <%= time_ago_in_words(cat.updated_at) %> ago</small>
          </div>
        </div>
      </div>  
    </div>
  <% end %>
</div>

<div class="flickr_pagination">
  <%= will_paginate @categories, :container => false %>
</div>

app/views/categories/new.html.erb
<h1 class="text-center mt-4">Create new catagory</h1>
<%= render 'form' %>

app/views/categories/show.html.erb
<h1 class="text-center mt-4">Catagory: <%= @category.name %></h1>

  <% if logged_in? && current_user.admin? %>
    <div class="text-center mt-4">
      <%= link_to "Edit Category name", edit_category_path(@category), class:"btn btn-outline-info" %>
    </div>
  <% end %>

  <h3 class="text-center mt-4">Articles</h3>

  <div class="flickr_pagination">
    <%= will_paginate @articles, :container => false %>
  </div>
  <%= render 'articles/article' %>
  <div class="flickr_pagination">
    <%= will_paginate @articles, :container => false %>
  </div>¯

app/views/layouts/_footer.html.erb
<footer id="sticky-footer" class="flex-shrink-0 py-4 bg-dark text-white">
  <div class="container text-center">
    <small>Copyright &copy; <%= link_to "GreeMm", "https://greemm.com", class: "text-white" %></small>
  </div>
</footer>

app/views/layouts/_messages.html.erb
<div class="container">
  <% flash.each do |name, msg| %>
    <div class="alert alert-<%= name == "notice" ? "success": "danger"%> alert-dismissible fade show" role="alert">
      <%= msg %>
      <button type="button" class="close" data-dismiss="alert" aria-label="Close">
        <span aria-hidden="true">&times;</span>
      </button>
    </div>
  <% end %> 
</div>

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-expand-lg">
  <div class="container-fluid">
   <!-- <a class="navbar-brand" id ="logo" href="#">Alpha Blog Geas</a>-->
    <%= link_to "ALPHA BLOG", root_path, class:"navbar-brand", id:"logo" %>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <%= link_to 'Bloggers List', users_path, class:"nav-link" %>
        </li>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            Article
          </a>
          <ul class="dropdown-menu">
            <% if logged_in? %>
              <%= link_to 'Create new article', new_article_path, class:"dropdown-item" %>
            <% end %>
            <%= link_to 'View article', articles_path, class:"dropdown-item" %>
            <li><hr class="dropdown-divider"></li>
            <li><a class="dropdown-item" href="#">Something else here</a></li>
          </ul>
        </li>

        <% if logged_in? %>

          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
              Categories
            </a>
            <ul class="dropdown-menu">
              <% if logged_in? && current_user.admin? %>
                <%= link_to 'Create new Category', new_category_path, class:"dropdown-item" %>
              <% end %>
              <%= link_to 'View Categories', categories_path, class:"dropdown-item" %>
            </ul>
          </li>

          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
              <%= "(Admin)" if current_user.admin?  %> Profile [<%= current_user.username %>]
            </a>
            <ul class="dropdown-menu">
              <%= link_to 'View your profile', user_path(current_user), class:"dropdown-item" %>
              <%= link_to 'Edit your profile', edit_user_path(current_user), class:"dropdown-item" %>
              <%= link_to 'Delete your profile', user_path(current_user), class:"dropdown-item text-danger", data: {confirm: "Eliminare l'utente?", turbo_method: :delete }  %>
            </ul>
          </li>
          <li class="nav-item">
            <%= link_to 'Logout', logout_path, class: "nav-link",  data: {confirm: "Eseguire il logout? ", turbo_method: :delete }  %>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to 'log In', login_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to 'Sign Up', signup_path, class: "nav-link" %>
          </li>
        <% end %>


      </ul>
      <form class="d-flex" role="search">
        <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
        <button class="btn btn-outline-success" type="submit">Search</button>
      </form>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>AlphaBlog</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>

  </head>

  <body class="d-flex flex-column">
    <%= render 'layouts/navigation' %>
    <div id="page-content">
      <%= render 'layouts/messages' %>
      <%= yield %>
    </div>
    <%= render 'layouts/footer' %>

  </body>
</html>

app/views/pages/about.html.erb
<h1>This is About of Alpha-blog site</h1>


<p>
  <%= link_to 'Return list', articles_path %>
</p>
<p>
  <%= link_to 'Home page', root_path %>
</p>

app/views/pages/home.html.erb
<div class="conteiner" id="home-conteiner">
    <div class="p-5 mb-4 bg-light rounded-3" id="jumbo">
      <div class="container-fluid py-5 text-center">
        <h1 class="display-5 fw-bold">Alpha Blog Geas</h1>
        <p class="col-md-12 fs-4 text-white">Using a series of utilities, you can create this jumbotron, just like the one in previous versions of Bootstrap. Check out the examples below for how you can remix and restyle it to your liking.</p>
        <%=  link_to 'Sign Up', signup_path, class:"btn btn-success btn-lg" %>
      </div>
    </div>
</div>

app/views/shared/_errors.html.erb
  
<% if obj.errors.any? %>
  <div class="alert alert-danger alert-dismissible fade show" role="alert">
    <h4 class="alert-heading">Questi errori non permettono il salavtaggio  <%= obj.class.name.downcase %></h4>
    <ul>
      <% obj.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end  %>
    </ul>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>

 

app/views/users/_form.html.erb
<div class="conteiner m-4">

  <div class="row justify-content-center">
    <div class="col-10">
      
      <%= render 'shared/errors', obj: @user %>

      <%= form_with(model: @user , data: {turbo:false} ,class:"shadow p-3 mb-5 bg-info rounded", local: true) do |f|  %>

        <div class="form_group row">
          <%= f.label :username, class: "col-2 col-form-label text-light"  %>
          <div class="col-10">
            <%= f.text_field :username, class: "form-control shadow rounded", placeholder:"Enter a Username" %> 
          </div>
        </div>
<br>
        <div class="form_group row">
          <%= f.label :email , class: "col-2 col-form-label text-light"  %>
          <div class="col-10">
            <%= f.email_field :email,class: "form-control shadow rounded" %>
          </div>
        </div>
<br>
        <div class="form_group row">
          <%= f.label :password , class: "col-2 col-form-label text-light"  %>
          <div class="col-10">
            <%= f.password_field :password, class: "form-control shadow rounded", placeholder:"Chose a password"  %>
          </div>
        </div>
<br>


        <div class="form_group row justify-content-center">
          <%= f.submit(@user.new_record? ? "Sign up" : "Update account" , class: "btn btn-outline-light btn-lg col-2") %>
        </div>

      <% end %>
      <div class="mb-3">
            <%= link_to 'Return list', articles_path %>
      </div>
    </div>
  </div>
</div>

app/views/users/_user.html.erb
<div class="conteiner">
  <% @users.each do |usr| %> 
    <div class="row justify-content-md-center">
      <div class="col-8 mt-4">
        <div class="card text-center shadow mb-5 bg-white rounded">
          <div class="card-header font-italic">
            <%= link_to usr.username, usr %>
          </div>
          <div class="card-body">
            <h5 class="card-title">
            <%= link_to gravatar_for( usr, size:150 ), usr %></h5>
            <p class="card-text"><%= pluralize(usr.articles.count, "article") %></p>
            <%= link_to "View Profile", usr, class:"btn btn-outline-success" %>
            <% if logged_in? && usr == current_user %>
              <%= link_to "Edit Profile", edit_user_path(usr), class:"btn btn-outline-info" %>
            <% end %>
          </div>
          <div class="card-footer text-muted">
            <small> Joined <%= time_ago_in_words(usr.created_at) %> ago, edited <%= time_ago_in_words(usr.updated_at) %> ago</small>
          </div>
        </div>
      </div>  
    </div>
  <% end %>
</div>

app/views/users/edit.html.erb
  <h1 class="text-center mt-4">Edit User</h1>

  <%= render 'form' %>

app/views/users/index.html.erb
<h1 class="text-center mt-4">Showing Users list</h1>

<div class="flickr_pagination">
  <%= will_paginate @users, :container => false %>
</div>
<%= render 'user' %>
<div class="flickr_pagination">
  <%= will_paginate @users, :container => false %>
</div>

app/views/users/new.html.erb
<h1 class="text-center mt-4">Sign up Alpha Blog - Create User</h1>
<%= render 'form' %>

app/views/users/show.html.erb
  <h1 class="text-center mt-4"><%= @user.username %></h1>

  <%= gravatar_for @user, size: 200 %>

  <% if logged_in? && @user == current_user %>
    <div class="text-center mt-4">
      <%= link_to "Edit Your Profile", edit_user_path(@user), class:"btn btn-outline-info" %>
    </div>
  <% end %>

  <h3 class="text-center mt-4">Articles</h3>

  <div class="flickr_pagination">
    <%= will_paginate @articles, :container => false %>
  </div>
  <%= render 'articles/article' %>
  <div class="flickr_pagination">
    <%= will_paginate @articles, :container => false %>
  </div>